import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProviderComponent } from './SessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <SessionProviderComponent>
                <body className="bg-stone-800 h-screen w-screen">{children}</body>
            </SessionProviderComponent>
        </html>
    );
}
